-- Your SQL goes here
ALTER TABLE users
ADD COLUMN salt TEXT NOT NULL;
ALTER TABLE users
ADD COLUMN password_hash TEXT NOT NULL;
ALTER TABLE users
ADD COLUMN email VARCHAR NOT NULL;
ALTER TABLE users
ADD COLUMN first_name VARCHAR NOT NULL;
ALTER TABLE users
ADD COLUMN last_name VARCHAR NOT NULL;
ALTER TABLE users DROP COLUMN hair_color;